import Foundation

struct ShortcutFileGenerator {

    // The shortcuts ALMS installs. Only Calendar still needs a Shortcut. Reminders are created
    // natively via EventKit (RemindersService), and file organization / Finder reveal are native too
    // (FinderService). Update/complete flows are intentionally omitted (the app never calls them yet).
    private static let definitions: [(name: String, plist: () -> [String: Any])] = [
        ("ALMS-CreateCalendarEvent", makeCreateCalendarEvent),
    ]

    /// Writes the 8 unsigned `.shortcut` plist files plus a bash script that signs and installs them,
    /// and returns the script's URL.
    ///
    /// Why a Terminal script instead of installing in-app: macOS only imports *signed* shortcut files
    /// (unsigned import was removed in macOS 13), and `shortcuts sign` needs Keychain access that a
    /// sandboxed app cannot get. Run from Terminal, the same command signs with the user's iCloud
    /// identity and the signed files install silently. The user runs this one script; we cannot.
    static func generateInstallScript() throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("ALMS-Shortcuts", isDirectory: true)
        try? FileManager.default.removeItem(at: dir)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        var lines: [String] = [
            "#!/bin/bash",
            "# Auto-generated by ALMS. Signs each shortcut with your iCloud identity and installs it.",
            "echo '── Installing ALMS shortcuts ──'",
            ""
        ]

        for (name, makePlist) in definitions {
            let unsigned = dir.appendingPathComponent("\(name)-unsigned.shortcut")
            let signed   = dir.appendingPathComponent("\(name).shortcut")
            let data = try PropertyListSerialization.data(
                fromPropertyList: makePlist(), format: .xml, options: 0
            )
            try data.write(to: unsigned)
            // No `set -e`: a failure on one (e.g. an optional flow) must not block the others.
            lines += [
                "echo '→ \(name)'",
                "if /usr/bin/shortcuts sign --input '\(unsigned.path)' --output '\(signed.path)' --mode people-who-know-me 2>/dev/null; then",
                "  open '\(signed.path)'",
                "  sleep 1.5",
                "else",
                "  echo '  (skipped — sign failed)'",
                "fi",
                ""
            ]
        }
        lines.append("echo '── Done. Return to ALMS and tap Verify Now. ──'")

        let script = lines.joined(separator: "\n")
        let scriptURL = dir.appendingPathComponent("install-alms-shortcuts.sh")
        try script.write(to: scriptURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptURL.path)
        return scriptURL
    }

    // MARK: - Helpers

    private static func text(_ s: String) -> [String: Any] {
        ["Value": ["string": s], "WFSerializationType": "WFTextTokenString"]
    }

    private static func ref(_ uuid: String) -> [String: Any] {
        [
            "Value": ["OutputUUID": uuid, "Type": "ActionOutput"],
            "WFSerializationType": "WFTextTokenAttachment"
        ]
    }

    /// Builds a WFTextTokenString that interpolates several action-output variables, joined by
    /// `separator`. Each variable occupies one U+FFFC (Object Replacement Character) in the string,
    /// and `attachmentsByRange` maps that character's {location, length} to the variable. This is how
    /// Shortcuts inlines variables inside a Text action.
    private static func combinedText(uuids: [String], separator: String) -> [String: Any] {
        let placeholder = "\u{FFFC}"
        var pieces: [String] = []
        var attachments: [String: Any] = [:]
        var cursor = 0
        for (i, uuid) in uuids.enumerated() {
            if i > 0 {
                pieces.append(separator)
                cursor += separator.utf16.count
            }
            attachments["{\(cursor), 1}"] = ["OutputUUID": uuid, "Type": "ActionOutput"]
            pieces.append(placeholder)
            cursor += 1
        }
        return [
            "Value": [
                "string": pieces.joined(),
                "attachmentsByRange": attachments
            ],
            "WFSerializationType": "WFTextTokenString"
        ]
    }

    /// A single variable wrapped as a text-field value. Text fields (a reminder's Title/Notes, an
    /// event's Title) require the variable *embedded in a WFTextTokenString* — a bare attachment
    /// (`ref`) reads as empty in a text field. Picker/input slots (List, WFInput) use `ref` instead.
    private static func varText(_ uuid: String) -> [String: Any] {
        combinedText(uuids: [uuid], separator: "")
    }

    private static func inputRef() -> [String: Any] {
        [
            "Value": ["Type": "ExtensionInput"],
            "WFSerializationType": "WFTextTokenAttachment"
        ]
    }

    private static func getDictAction(uuid: String) -> [String: Any] {
        [
            "WFWorkflowActionIdentifier": "is.workflow.actions.detect.dictionary",
            "WFWorkflowActionParameters": [
                "UUID": uuid,
                "WFInput": inputRef()
            ]
        ]
    }

    private static func getValueAction(uuid: String, key: String, fromUUID: String) -> [String: Any] {
        // NOTE: "Get Dictionary Value" is is.workflow.actions.getvalueforkey on macOS Tahoe —
        // NOT "getdictionaryvalue" (that string causes "Unknown Action"). Key param is WFDictionaryKey.
        [
            "WFWorkflowActionIdentifier": "is.workflow.actions.getvalueforkey",
            "WFWorkflowActionParameters": [
                "UUID": uuid,
                "WFGetDictionaryValueType": "Value",
                "WFDictionaryKey": text(key),
                "WFInput": ref(fromUUID)
            ]
        ]
    }

    private static func wrap(name: String, actions: [[String: Any]]) -> [String: Any] {
        [
            "WFWorkflowName": name,
            "WFWorkflowClientVersion": "2600.0.0.0",
            "WFWorkflowMinimumClientVersion": 900,
            "WFWorkflowMinimumClientVersionString": "900",
            "WFWorkflowHasShortcutInputVariables": true,
            "WFWorkflowImportQuestions": [] as [Any],
            "WFWorkflowInputContentItemClasses": [
                "WFStringContentItem",
                "WFDictionaryContentItem",
                "WFFileContentItem"
            ],
            "WFWorkflowOutputContentItemClasses": [] as [Any],
            "WFWorkflowTypes": [] as [Any],
            "WFWorkflowIcon": [
                "WFWorkflowIconGlyph": 59511,
                "WFWorkflowIconStartColor": 946233655
            ] as [String: Any],
            "WFWorkflowActions": actions
        ]
    }

    // MARK: - Shortcut Definitions

    private static func makeCreateCalendarEvent() -> [String: Any] {
        let d = UUID().uuidString
        let t = UUID().uuidString
        let s = UUID().uuidString
        let c = UUID().uuidString
        let n = UUID().uuidString

        return wrap(name: "ALMS-CreateCalendarEvent", actions: [
            getDictAction(uuid: d),
            getValueAction(uuid: t, key: "title",      fromUUID: d),
            getValueAction(uuid: s, key: "start_date", fromUUID: d),
            getValueAction(uuid: c, key: "calendar",   fromUUID: d),
            getValueAction(uuid: n, key: "notes",      fromUUID: d),
            [
                // "Add New Event" = is.workflow.actions.addnewevent, params use WFCalendarItem* prefix.
                // Title/Notes are text fields (varText); Calendar is a picker (bare ref).
                "WFWorkflowActionIdentifier": "is.workflow.actions.addnewevent",
                "WFWorkflowActionParameters": [
                    "WFCalendarItemTitle":     varText(t),
                    "WFCalendarItemStartDate": varText(s),
                    "WFCalendarItemCalendar":  ref(c),
                    "WFCalendarItemNotes":     varText(n),
                    "WFCalendarItemAllDay":    true
                ]
            ]
        ])
    }

}
